### ISSUE TITLE
Building documentation

### ISSUE THREAD

**Issue by teemuvesala** [smilligan93/SR5-Compendiums-FoundryVTT#10]
Hi,

I'd like to contribute to the project, but one important thing should be added as soon as possible: Simple steps to build the project so that it's easy to just use `ln -s ~/mydev data/System/shadowrun5e` and then just hacketi hack the code and save it and get it visible to the Foundry VTT as quickly as possible. I've got plenty of own needs which could help also others.

**Comment by smilligan93** [comment]
archiving this repo. code has been moved to the Shadowrun5e system.
